### PR TITLE
traducir syllabus (solo Unix y Git)

### PR DESCRIPTION
**Pull request by raynamharris**
según https://github.com/Carpentries-ES/workshop-template-es/issues/18

### CODE REVIEW

**Review by orchid00 — CHANGES_REQUESTED** [review]
i'm a bit confused
<li>Files and directories</li>
<li>History and tab completion</li>

should be
<li>Archivos y directorios</li>
<li>Historia y autocompletar</li>

**Comment by raynamharris** [comment]
@orchid00 No traduje las palabras. Copié los títulos del episodio. No sé qué es más correcto ...

**Comment by orchid00** [comment]
still confused, from where did you copy? if it isn't translation then it might be alright

**Comment by raynamharris** [comment]
I copied it from the "horario" on the main page of the lesson website.
https://swcarpentry.github.io/shell-novice-es/

**Comment by orchid00** [comment]
then it is alright

**Comment by raynamharris** [comment]
Closing this PR because all translations have been done (more appropriately) in the style-es file.

**Pull request closed without merging**
